compressionLevel: mixed

enableGlobalCache: false

plugins:
  - checksum: dfdf672506546b93e5bd2b984395db98fec7bb0024bb170de3c57e5569447e52bc8e256a447e16d5fdf240072ac2d5507bb9bb4c237a6f882a706b7aa4637412
    path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: bundles/@yarnpkg/plugin-engines.js

yarnPath: .yarn/releases/yarn-4.1.1.cjs
